services:
  auth-app-dev:
    image: lambki/auth-app-dev:latest
    container_name: auth-app-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        - NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH}
    restart: unless-stopped
    ports:
      - "${APP_PORT:-13203}:3000"
    networks:
      - my-shared-proxy-net
    # Mount source code as volume for hot reload
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    # Loads all variables from .env.development into the container
    env_file:
      - .env
    environment:
      # Node environment (defaults to development if not set)
      NODE_ENV: ${NODE_ENV:-development}
      NEXT_PUBLIC_BASE_PATH: ${NEXT_PUBLIC_BASE_PATH}
      POSTGRES_URL: ${POSTGRES_URL}
      DATABASE_SSL: ${DATABASE_SSL:-false}
      DEBUG: ${DEBUG:-postgres:*}
      # Enable polling for file watching (required for hot reload in Docker)
      WATCHPACK_POLLING: ${WATCHPACK_POLLING:-true}
      CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING:-true}
    profiles:
      - dev

  auth-app-prod:
    image: lambki/auth-app-prod:latest
    container_name: auth-app-prod
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH}
    restart: unless-stopped
    ports:
      - "${APP_PORT:-13203}:3000"
    networks:
      - my-shared-proxy-net
    # Loads all variables from .env.production into the container
    env_file:
      - .env
    environment:
      # Node environment (defaults to production if not set)
      NODE_ENV: ${NODE_ENV:-production}
      NEXT_PUBLIC_BASE_PATH: ${NEXT_PUBLIC_BASE_PATH:-/auth}
      POSTGRES_URL: ${POSTGRES_URL}
      DATABASE_SSL: ${DATABASE_SSL:-false}
      DEBUG: ${DEBUG:-false}
    profiles:
      - prod

networks:
  my-shared-proxy-net:
    external: true
